### ISSUE TITLE
Override doesn’t get the correct typing

### ISSUE THREAD

**Issue by lughino** [jackfranklin/test-data-bot#270]
Hi @jackfranklin  ,
When I try to `override` a build, the override object doesn’t receive the type passed to the builder. 
I think it’s related to the declaration of the interface:
```typescript
interface Overrides<FactoryResultType> {
  [x: string]: Field;
}
```

Which it should be something like:
```typescript
type Overrides<FactoryResultType> = {
  [x in keyof Partial<FactoryResultType>]: ValueOf<FactoryResultType>
}
```

**Comment by lughino** [comment]
@jackfranklin do you have any plans for this to be fixed?
The override functionality is not usable with typescript.

**Comment by kimroen** [comment]
The types for `Override` is a little more complicated than that, because not only can the value be a straight-up value matching the original, in the context of a Trait it can also be a `faker` or `perBuild` function. Maybe something like a `Field` that is aware of a specific type its builders should return is something to consider?

**Comment by jtmclucas13** [comment]
Just want to +1 this. I love test-data-bot so far but it's TypeScript limitations are a challenge! My current workaround is to create a modified type that I'm casting the result to. It's unfortunate because it requires the maintenance of a new type.

A modified generic example:

```
type Definition = {
    property: string | null,
};

type ModifiedDefinition = Omit<
	Definition,
	'property'
> & { property: string };

...

const myTestObject = (definitionBuilder({
    overrides: {
        property: fake(f => f.lorem.paragraph()),			},
    }) as ModifiedDefinition)
```

**Comment by jackfranklin** [comment]
I have struggled since day one with the TS types for this library - it's been a challenge to get it right! 

We definitely should limit the keys in `Overrides` to be values in the original definition, so that's probably a good place to start. I'd welcome any guidance from TS experts as maintaining the full type safety has always been tough given what this library sets out to do.

**Comment by jackfranklin** [comment]
I think v2's types should improve this greatly. Please open a new issue if there are still problems here.
