### ISSUE TITLE
Type of build is not created based on postBuild param

### ISSUE THREAD

**Issue by nsantos16** [jackfranklin/test-data-bot#498]
Hey 👋   I wondering if this issue is a particular problem of mine or is something we can add/fix on future contributions.

When I created `accountBuilder` the type that is returned not include `accountType`, is the `postBuild` not adding new types to the build function?
```
const accountTypeBuilder = build('AccountType', {
  fields: {
    id: sequence(),
    name: fake(f => f.random.arrayElement(getAccountTypesValues())),
    createdAt: fake(f => f.date.past),
    updatedAt: fake(f => f.date.past),
  },
});

const accountBuilder = build('Account', {
  fields: {
    id: sequence(),
    name: fake(f => f.finance.accountName),
    officialName: fake(f => f.finance.accountName),
    institution: fake(f => f.company.companyName),
    createdAt: fake(f => f.date.past),
    updatedAt: fake(f => f.date.past),
    closed: bool(),
  },
  postBuild: account => {
    const accountType = accountTypeBuilder();

    return {...account, accountType };
  }
});

```

**Comment by jackfranklin** [comment]
@nsantos16 hey, thanks for the issue. Is your question here that the TypeScript type of `accountBuilder` is wrong because it doesn't include the keys from the `accountType` ? 

Unfortunately I'm not that's going to be an easy fix, but we could look at making `postBuild` take a generic:

```ts
postBuild: <AccountWithTypeFields>(account) => {...}
```

Where that would then be the return type. wdyt?

**Comment by jackfranklin** [comment]
Closing due to age; please open a new issue if you'd like to discuss further. Thanks!
